package entity;

// Generated 2013-4-3 10:50:57 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSRole generated by hbm2java
 */
@Entity
@Table(name = "t_s_role", catalog = "jeecgv3")
public class TSRole implements java.io.Serializable {

	private String id;
	private String rolename;
	private String rolecode;

	public TSRole() {
	}

	public TSRole(String id) {
		this.id = id;
	}

	public TSRole(String id, String rolename, String rolecode) {
		this.id = id;
		this.rolename = rolename;
		this.rolecode = rolecode;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "rolename", length = 20)
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@Column(name = "rolecode", length = 15)
	public String getRolecode() {
		return this.rolecode;
	}

	public void setRolecode(String rolecode) {
		this.rolecode = rolecode;
	}

}
