package entity;

// Generated 2013-4-3 10:50:57 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSRoleUser generated by hbm2java
 */
@Entity
@Table(name = "t_s_role_user", catalog = "jeecgv3")
public class TSRoleUser implements java.io.Serializable {

	private String id;
	private String userid;
	private String roleid;

	public TSRoleUser() {
	}

	public TSRoleUser(String id) {
		this.id = id;
	}

	public TSRoleUser(String id, String userid, String roleid) {
		this.id = id;
		this.userid = userid;
		this.roleid = roleid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "userid", length = 32)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "roleid", length = 32)
	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

}
